### ISSUE TITLE
Using Gsap Scroll Trigger with data-scroll-section

### ISSUE THREAD

**Issue by MaxVeilleuxMTL** [DidoMarchet/starter-kit-nuxt-locomotive-scroll#3]
Is there some way to make `data-scroll-section` (for performance reasons) work with Gsap Scroll Trigger?

**Comment by DidoMarchet** [comment]
Hi!
I've just added `data-scroll-section` to the sections of the Scroll Trigger example.
I think `data-scroll-section` doesn't increase performance with Scroll Trigger because it works with the giving scroll position but add it it's not a bad idea.
For more details I advice to check or ask to creators. 

Have a nice day and regards,
Davide
